const assert=require('node:assert/strict');
const {advance,NoticeTracker}=require('../static/notifications.js');
const values=new Map(),storage={getItem:k=>values.has(k)?values.get(k):null,setItem:(k,v)=>values.set(k,v)};
let tracker=new NoticeTracker(storage,'test');
assert.deepEqual(tracker.consume([{event_id:4}]),[],'initial pending requests are baseline');
assert.deepEqual(tracker.consume([{event_id:4},{event_id:7}]),[7]);
assert.deepEqual(tracker.consume([{event_id:4},{event_id:7}]),[],'poll does not repeat');
tracker=new NoticeTracker(storage,'test');
assert.deepEqual(tracker.consume([{event_id:4},{event_id:7}]),[],'reload does not repeat');
assert.deepEqual(tracker.consume([]),[]);
assert.deepEqual(tracker.consume([{event_id:9}]),[9],'new request after reversion has new event');
assert.deepEqual(advance(9,[1,8,-1,NaN,'10']).fresh,[]);
const otherTab=new NoticeTracker(storage,'test');
assert.deepEqual(otherTab.consume([{event_id:9}]),[],'another tab observes stored cursor');
const independent=new NoticeTracker(storage,'new-scope');
assert.deepEqual(independent.consume([]),[]);assert.deepEqual(independent.consume([{event_id:1}]),[1],'cleanup namespace starts a new stream');
const unavailable=new NoticeTracker({getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}},'blocked');
assert.deepEqual(unavailable.consume([]),[]);assert.deepEqual(unavailable.consume([{event_id:2}]),[2]);assert.deepEqual(unavailable.consume([{event_id:2}]),[]);
console.log('Notification tracking: baseline, new event, poll, reload, resolved/re-requested, tabs, namespace and unavailable storage passed.');
